public class Warrior
{
    /* Fields are mostly used for internal use while properties are used mostly for external use.   */

    // Fields - private access modifiers to make sure it can be accessible only within the class.
    private int height; // fields small letter.
    private int weight;

    public int Height { get; set; } // properties start with capital letter.
    public int Weight { get; set; } // type prop and enter to get autogenerated property.
}

public class Program
{
    static void Main()
    {
        Warrior theGoodGuy = new Warrior();
        theGoodGuy.Height = 190;
        theGoodGuy.Weight = 80;

        Warrior theBadGuy = new Warrior();
        theBadGuy.Height = 170;
        theBadGuy.Weight = 100;

        Console.WriteLine(theGoodGuy.Height);
        Console.WriteLine(theBadGuy.Height);
    }
}