public class Warrior
{
    /* Fields are mostly used for internal use while properties are used mostly for external use.   */

    // Fields - private access modifiers to make sure it can be accessible only within the class.
    private int height; // fields small letter.
    private int weight;
    private string name;

    public int Height { get; set; } // properties start with capital letter.
    public int Weight { get; set; } // type prop and enter to get autogenerated property.
    public string Name { get; set; }

    // Constructors are public
    public Warrior(int height, int weight, string name)
    {
        Height = height;
        Weight = weight;
        Name = name;
    }

    public void Greetings(Warrior warrior) // passed object as an argument
    {
        System.Console.WriteLine($"Greetings, {warrior.Name}");
    }
}

public class Program
{
    static void Main()
    {
        Warrior theGoodGuy = new Warrior(190, 80, "Good Guy");
        Warrior theBadGuy = new Warrior(170, 100, "Bad Guy");

        Console.WriteLine(theGoodGuy.Height);
        Console.WriteLine(theBadGuy.Height);

        theGoodGuy.Greetings(theBadGuy); 
    }
}