namespace Characters.Warriors
{
    public class Warrior
    {
        /* Fields are mostly used for internal use while properties are used mostly for external use.   */

        // Fields - private access modifiers to make sure it can be accessible only within the class.
        private int height; // fields small letter.
        private int weight;
        private string name;
        private int age;

        // properties start with capital letter.
        // get and set are accessors.
        public int Height 
        { 
            get
            {
                return height;
            }
            set
            {
                height = value;
            }
        } 
        public int Weight { get; set; } // type prop and enter to get autogenerated property.
        public string Name 
        {
            get
            {
                return name;
            }
            set
            {
                name = value;
            }
        }
        public int Age
        {
            get
            {
                return age;
            }
            set
            {
                if (value >= 18 && value <= 45)
                {
                    age = value;
                }
                else
                {
                    System.Console.WriteLine($"The selected age for {name} is not proper age of warrier. It should be between 18 and 45.");
                }
            }
        }

        // Constructors are public
        public Warrior(int height, int weight, string name)
        {
            Height = height;
            Weight = weight;
            Name = name;
        }

        public void Greetings(Warrior warrior) // passed object as an argument
        {
            Console.WriteLine($"Greetings, {warrior.Name}");
        }
    }
}
